name: Deploy to Google App Engine upon commit to master branch and on schedule at midnight UTC
run-name: Deployment triggered by ${{ github.event_name }} / ${{ github.actor }}

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron:  '0 0 * * *' # every day at midnight UTC 
    # see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  workflow_dispatch:
  
jobs:
  default-job:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Triggered by ${{ github.event_name }} event."
      - run: echo "Branch is ${{ github.ref }}"
      
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Setup Sentry CLI
        uses: mathieu-bour/setup-sentry-cli@1.2.0
        with:
          version: latest # optional if 'latest'
          token: ${{ SECRETS.SENTRY_AUTH_TOKEN }} # from GitHub secrets
          
      - id: 'auth'
        name: 'Authenticate Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ SECRETS.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ SECRETS.GCP_SERVICE_ACCOUNT }}

      - name: 'Set up Google Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        
      - name: Deploy to production
        run: ./deploy.sh react --env=production
          
      - run: echo "Job status is ${{ job.status }}."
