name: Sync *-deploy fork with latest changes in this repo
run-name: Sync *-deploy fork triggered by ${{ github.event_name }} / ${{ github.actor }}

on:
  push:
    branches:
      - 'master'
    
jobs:
  default-job:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Triggered by ${{ github.event_name }} event."
      - run: echo "Branch is ${{ github.ref }}"
      
      - name: Check out `application-monitoring-deploy`
        uses: actions/checkout@v3
        with:
          repository: sentry-demos/application-monitoring-deploy
          fetch-depth: 0
          token: ${{ secrets.KOSTY_PERSONAL_ACCESS_TOKEN_FOR_SYNC_DEPLOY_FORK }}

      
      - name: Add and fetch *this* repo (`sentry-demos/application-monitoring`)
        run: git remote add -f upstream https://github.com/sentry-demos/application-monitoring
        
      - name: Configure User email
        run: |
            git config --global user.email "kosty.maleyev@sentry.io"
            git config --global user.name "sync-deploy-fork on behalf of Kosty Maleyev"
          
      - name: Merge in latest changes
        run: git rebase upstream/master || git diff --diff-filter=U --relative
      
      - name: Push (force)
        run: git push -f
      
      - run: echo "Job status is ${{ job.status }}."
